# Generated by Django 3.0.8 on 2020-10-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='website',
            new_name='subject',
        ),
    ]
