# Generated by Django 3.0.8 on 2021-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commission',
            field=models.CharField(default='15%', max_length=50),
        ),
    ]
