# Generated by Django 3.0.8 on 2021-01-06 10:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210106_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
