# Generated by Django 3.0.8 on 2020-10-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201014_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
