# Generated by Django 2.2 on 2021-07-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210713_1355"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscribers",
        ),
    ]
