# Generated by Django 3.0.8 on 2021-01-13 11:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210113_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expert_countries',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_advice',
            field=ckeditor.fields.RichTextField(default=-1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
