# Generated by Django 2.2 on 2021-03-07 11:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_title', models.CharField(blank=True, max_length=500)),
                ('welcome_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('welcome_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('happy_travellers', models.PositiveIntegerField(blank=True, null=True)),
                ('satisfied_tours', models.PositiveIntegerField(blank=True, null=True)),
                ('total_destination', models.PositiveIntegerField(blank=True, null=True)),
                ('choose_info', models.ManyToManyField(blank=True, null=True, to='office.ChooseUs')),
            ],
        ),
    ]
