# Generated by Django 2.2 on 2021-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us Info'},
        ),
        migrations.AlterModelOptions(
            name='chooseus',
            options={'verbose_name_plural': 'Why Choose Info'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='choose_info',
            field=models.ManyToManyField(blank=True, null=True, to='office.ChooseUs', verbose_name='Choose InfoAdd only three infos'),
        ),
    ]
