# Generated by Django 2.2 on 2021-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20210307_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='choose_info',
            field=models.ManyToManyField(blank=True, null=True, to='office.ChooseUs', verbose_name='Choose Info(Add only three infos)'),
        ),
    ]
