# Generated by Django 2.2 on 2021-03-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='native_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
