# Generated by Django 2.2 on 2021-03-08 07:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_testimonial_native_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('join_title1', models.CharField(blank=True, max_length=255, null=True)),
                ('description_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('join_title2', models.CharField(blank=True, max_length=255, null=True)),
                ('description_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('join_title3', models.CharField(blank=True, max_length=255, null=True)),
                ('description_3', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
