# Generated by Django 2.2 on 2021-03-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Potential Partners',
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partner Info'},
        ),
    ]
