# Generated by Django 2.2 on 2021-03-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20210308_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='happy_travellers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='satisfied_tours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='total_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
