# Generated by Django 2.2 on 2021-03-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20210308_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='welcome_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
