branch-defaults:
  master:
    environment: bonholidays-dev
    group_suffix: null
environment-defaults:
  bonholidays-dev:
    branch: null
    repository: null
global:
  application_name: bonholidays
  branch: null
  default_ec2_keyname: bonholidaysaws
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
