# Generated by Django 2.2 on 2021-07-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("video", models.FileField(blank=True, null=True, upload_to="")),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
