# Generated by Django 3.0.7 on 2020-06-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('duration', models.IntegerField(null=True)),
                ('no_of_persons', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
