# Generated by Django 3.0.8 on 2021-01-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='new_activity',
            field=models.CharField(choices=[('Custom-made trip with guide and/or driver', 'Custom-made trip with guide and/or driver'), ('Custom-made trip without guide and driver', 'Custom-made trip without guide and driver'), ('Group Tour', 'Group Tour'), ('Cruise Tour', 'Cruise Tour')], default='Trekking', max_length=100),
        ),
    ]
