# Generated by Django 3.0.8 on 2020-11-11 05:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='highlights',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='itinerary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='reviews',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
