# Generated by Django 3.0.8 on 2021-03-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [



        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.IntegerField(default=15, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail Image-Vertical'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image-Horizontal'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image-Square'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image-Sqaure'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(verbose_name='Price in Nrs'),
        ),
    ]
