# Generated by Django 3.0.8 on 2020-10-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopActivities',
        ),
    ]
