# Generated by Django 3.0.8 on 2020-12-18 05:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='exclusions',
            field=ckeditor.fields.RichTextField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=ckeditor.fields.RichTextField(default=-1),
            preserve_default=False,
        ),
    ]
