# Generated by Django 3.0.8 on 2021-07-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20210307_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-id',)},
        ),
    ]
