# Generated by Django 3.0.8 on 2020-11-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
        ),
    ]
