# Generated by Django 3.0.8 on 2020-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20201218_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
