# Generated by Django 3.0.8 on 2021-01-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_new_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='new_activity',
            field=models.CharField(default='Trekking', max_length=255),
        ),
    ]
