# Generated by Django 2.2 on 2021-07-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hours If One day Tour'),
        ),
    ]
