# Generated by Django 3.0.8 on 2020-12-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='user_rating',
        ),
    ]
