# Generated by Django 3.0.8 on 2020-11-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20201119_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.Package'),
        ),
    ]
