# Generated by Django 3.0.8 on 2021-01-05 08:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20201227_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary_text',
            field=ckeditor.fields.RichTextField(default=-1),
            preserve_default=False,
        ),
    ]
