# Generated by Django 2.2 on 2021-07-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20210712_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='destinations',
            field=models.ManyToManyField(related_name='packages', to='packages.Destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='packages.Destination'),
        ),
    ]
