# Generated by Django 3.0.8 on 2021-01-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20210115_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newactivity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='package',
            name='city',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
