# Generated by Django 3.0.8 on 2021-01-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20210115_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newactivity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
