# Generated by Django 3.0.8 on 2021-01-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20210105_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=models.ManyToManyField(to='packages.Itinerary'),
        ),
    ]
