# Generated by Django 3.0.8 on 2020-12-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20201221_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=models.ManyToManyField(to='packages.Itinerary'),
        ),
    ]
