# Generated by Django 3.0.8 on 2020-11-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20201119_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topactivities',
            name='destination',
        ),
    ]
