# Generated by Django 3.0.8 on 2021-01-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20210117_2153'),
        ('packages', '0005_auto_20210119_1548'),
    ]

    operations = [
    ]
