# Generated by Django 3.0.8 on 2021-01-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='itinerary_text',
        ),
    ]
