# Generated by Django 3.0.8 on 2020-11-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_remove_topactivities_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topactivities',
            name='title',
        ),
        migrations.AddField(
            model_name='topactivities',
            name='package',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='packages.Package'),
            preserve_default=False,
        ),
    ]
