# Generated by Django 3.0.8 on 2020-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20201119_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='activities_title',
            field=models.CharField(choices=[('travel_news', 'Travel News'), ('travel_tips', 'Travel Tips'), ('things_to_do', 'Things to Do'), ('places_to_go', 'Places to Go')], default=-1, max_length=64),
            preserve_default=False,
        ),
    ]
