# Generated by Django 3.0.8 on 2021-01-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_merge_20210124_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('North America', 'North America'), ('South America', 'South America'), ('Africa', 'Africa'), ('Ocenia', 'Ocenia'), ('Polar', 'Polar'), ('Regions', 'Regions')], default='Europe', max_length=255),
        ),
    ]
