# Generated by Django 3.0.8 on 2020-11-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_package_activities_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='activities_title',
        ),
        migrations.AddField(
            model_name='topactivities',
            name='title',
            field=models.CharField(default=-1, max_length=64),
            preserve_default=False,
        ),
    ]
