# Generated by Django 3.0.8 on 2021-01-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_destination_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('North America', 'North America'), ('South America', 'South America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Polar', 'Polar'), ('Regions', 'Regions')], default='Europe', max_length=255),
        ),
    ]
