# Generated by Django 3.0.8 on 2021-01-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20210105_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='special_discount',
            new_name='fix_departure',
        ),
    ]
