# Generated by Django 2.2 on 2021-07-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_destination_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='fixed_price_dollar',
            field=models.IntegerField(default=-1, verbose_name='Price in $ for fixed departures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='fixed_price_nrs',
            field=models.IntegerField(default=-1, verbose_name='Price in Nrs for fixed departures'),
            preserve_default=False,
        ),
    ]
