# Generated by Django 3.0.8 on 2020-11-23 07:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20201119_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topactivities',
            old_name='title',
            new_name='activity',
        ),
        migrations.AlterField(
            model_name='topactivities',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topactivities',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='packages.Package'),
        ),
    ]
