# Generated by Django 2.2 on 2021-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20210128_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail Image-Vertical'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image-Horizontal'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image-Square'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image-Sqaure'),
        ),
    ]
