# Generated by Django 2.2 on 2021-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20210212_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_2',
            field=models.IntegerField(default=-1, verbose_name='Price in $'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(verbose_name='Price in Nrs'),
        ),
    ]
