# Generated by Django 2.2 on 2021-02-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_auto_20210224_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='savings',
        ),
        migrations.RemoveField(
            model_name='package',
            name='tour_type',
        ),
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.IntegerField(default=15, verbose_name='Discount %'),
        ),
    ]
