# Generated by Django 2.2 on 2021-07-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_subscribed", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Newsletter Subscribers",
            },
        ),
    ]
