# Generated by Django 3.0.8 on 2020-12-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='caption',
            field=models.CharField(default=-1, max_length=500),
            preserve_default=False,
        ),
    ]
