# Generated by Django 2.2 on 2021-08-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20210726_1048'),
        ('blogs', '0002_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.Destination'),
        ),
    ]
