# Generated by Django 3.0.8 on 2020-12-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201221_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(to='blogs.Tag'),
        ),
    ]
