# Generated by Django 3.0.8 on 2020-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201119_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(default='travel', max_length=255),
        ),
    ]
