# Generated by Django 3.0.8 on 2020-11-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('booking', '0002_auto_20201106_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='blog',
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='packages.Package'),
            preserve_default=False,
        ),
    ]
