# Generated by Django 3.0.8 on 2020-12-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201225_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
