# Generated by Django 3.0.8 on 2020-12-01 04:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(choices=[('Single', 'Single'), ('Couple', 'Couple'), ('Family', 'Family'), ('Group', 'Group')], default='Couple', max_length=64)),
                ('number_of_children', models.IntegerField(default=0)),
                ('number_of_adults', models.IntegerField(default=0)),
                ('geographical_area', models.CharField(max_length=255)),
                ('bookedfor', models.DateField(blank=True)),
                ('age_group', models.CharField(choices=[('18-35 yrs', '18-35 yrs'), ('36-50 yrs', '36-50 yrs'), ('51-64 yrs', '51-64 yrs'), ('65+ yrs', '65+ yrs')], default='18-35 yrs', max_length=64)),
                ('tour_type', models.CharField(choices=[('With Guide/Driver', 'With Guide/Driver'), ('Without Guide/Driver', 'Without Guide/Driver'), ('Group Tour', 'Group Tour'), ('Cruise Tour', 'Cruise Tour')], default='Group Tour', max_length=100)),
                ('accomodation', models.CharField(choices=[('Basic', 'Basic'), ('Comfortable', 'Comfortable'), ('Luxury', 'Luxury'), ('Quirky', 'Quirky')], default='Comfortable', max_length=100)),
                ('budget', models.FloatField()),
                ('budget_flexibility', models.CharField(choices=[('No,this is my max budget', 'No,this is my max budget'), ('I can increase upto 20%', 'I can increase upto 20%'), ('Very flexible, plan me the best', 'Very flexible, plan me the best')], default='I can increase upto 20%', max_length=255)),
                ('Trip_stage', models.CharField(choices=[('I need more information before I can start trip planning', 'I need more information before I can start trip planning'), ('Iam ready to start trip planning', 'Iam ready to start trip planning'), ('I have done my homework and almost ready to book', 'I have done my homework and almost ready to book')], default='Iam ready to start trip planning', max_length=255)),
                ('trip_title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
