# Generated by Django 3.0.8 on 2020-12-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201221_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='bookedfor',
            field=models.DateField(blank=True, null=True),
        ),
    ]
