# Generated by Django 3.0.8 on 2020-12-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_custombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='accomodation',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Comfortable', 'Comfortable'), ('Luxury', 'Luxury'), ('Quirky', 'Quirky')], default='Quirky', max_length=100),
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='tour_type',
            field=models.CharField(choices=[('Custom-made trip with guide and/or driver', 'Custom-made trip with guide and/or driver'), ('Custom-made trip without guide and driver', 'Custom-made trip without guide and driver'), ('Group Tour', 'Group Tour'), ('Cruise Tour', 'Cruise Tour')], default='Group Tour', max_length=100),
        ),
    ]
