# Generated by Django 3.0.8 on 2020-12-03 06:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201203_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombooking',
            name='geographical_area',
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='budget',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='custombooking',
            name='trip_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
