# Generated by Django 3.0.8 on 2020-12-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20201206_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombooking',
            name='Trip_stage',
            field=models.CharField(choices=[('I need more information before I can start trip planning', 'I need more information before I can start trip planning'), ("I'm ready to start trip planning", "I'm ready to start trip planning"), ("I've done my homework and almost ready to book", "I've done my homework and almost ready to book")], default='Flexible,I can increase up to 20%,if needed', max_length=255),
        ),
    ]
