# Generated by Django 3.0.8 on 2020-12-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacted',
        ),
        migrations.AddField(
            model_name='contactform',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
