# Generated by Django 3.0.8 on 2020-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_auto_20201225_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contacted',
            field=models.BooleanField(null=True),
        ),
    ]
