# Generated by Django 3.0.8 on 2020-12-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20201225_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
