# Generated by Django 3.0.8 on 2020-12-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_auto_20201225_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='contacted',
        ),
    ]
