# Generated by Django 3.0.8 on 2020-12-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_remove_feedback_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
