# Generated by Django 3.0.8 on 2020-11-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='special_discout',
            new_name='special_discount',
        ),
    ]
