# Generated by Django 3.0.8 on 2020-10-10 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_delete_topactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Destination')),
            ],
        ),
    ]
