# Generated by Django 3.0.8 on 2020-10-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_topactivities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopAttractions',
        ),
    ]
