# Generated by Django 3.0.8 on 2020-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_delete_topattractions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopAttractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
    ]
