# Generated by Django 3.0.8 on 2020-10-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_package_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='featured',
        ),
        migrations.AddField(
            model_name='destination',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
